services:
    app:
        command: air
        build:
            context: .
            dockerfile: Dockerfile.dev
        stop_grace_period: 30s
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./:/app
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        image: postgres:17
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: database
        healthcheck:
            test: "pg_isready -U admin -d database"
            interval: 2s
            timeout: 5s
            retries: 10
    adminer:
        image: adminer:5.2.1
        restart: unless-stopped
        ports:
            - "8088:8080"
        environment:
            ADMINER_DEFAULT_SERVER: postgres
    mail1:
        image: analogic/poste.io:latest
        ports:
            - "143:143" # IMAP
            - "587:587" # SMTP
            - "8090:80"
            - "8443:443" # WEB UI
        volumes:
            - poste1-data:/data
        environment:
            VIRTUAL_HOST: mail1.local
            LETSENCRYPT_HOST: mail1.local
volumes:
    postgres-data:
        driver: local
    poste1-data:
        driver: local
